---
title: "ADR 2: Two download functions that return full datasets by default"
author: "Katrin Leinweber"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{"ADR 2: Two download functions that return full datasets by default"}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Context 

The [BacDive Web Service](https://bacdive.dsmz.de/api/bacdive/) accepts 4 types 
of requests and replies in 3 different ways:

request type | unambiguous? | JSON-reply
-------------|:------------:|--------
`taxon`      |           no | URL(s) of matching strain(s)
`sequence`   |          yes | URL of matching strain
`culturecollectionno` | yes | URL of matching strain
`bacdive_id` |          yes | dataset of that strain

The [advanced search](https://bacdive.dsmz.de/AdvSearch) has an option called
"Download list of BacDive Ids", which returns a text file with one `bacdive_id`
per line.


## Decision 

Because:

a) we assume that most users want to analyse the strain datasets, not lists of 
   URLs or IDs, and 
a) the request types seem to form a funnel from search to URL/ID to dataset,

we will ensure that all main functions return full dataset(s) by default.


## Status: Removed in [v0.9.0](../news/#bacdiver-090)


## Consequences

A uniform data structure was needed and implemented, see #31. In case IDs need to be retrieved, `retrieve_data()` and `retrieve_search_results()` either need an extra parameter for that, or a `retrieve_IDs()` function needs to be added (see #54)
